### ISSUE TITLE
Functional Specifications - Typos

### ISSUE THREAD

**Issue by EnzoGuillouche** [algosup/2023-2024-project-4-sportshield-team-2#21]
### Severity

2 - High

### Issue seen

Persona 1 - Ashley Ricks
line 105 - "She needs to be notice if someone touch to her skies."

Persona 2 - William Greener
line 126 - "He wants to get used to use the project."
line 131 - "William needs a product which won't burn under the sun's heat of Canary islandes."

Persona 3 - Steve Sinclair
line 145 - "He wants to protect his stuff will he is not in his camping-car."

Acceptance Criteria 
line 157 - "The electromagnet mustn't stay locked if the user want to take back his stuff."
line 159 - "The Alarm must to be able to be disabled without waiting if the user made a misstake."
line 161 - "The Battery must stay alive for 7 days or more."
line 163 - "It must run without any issues, If this event happen it need to catch them and alert the user of the error."
line 165 - "To ensure that the project is viable, all the specifications must be approved by the client and the the programs must be tested in intern by our Quality Assurance and potentially others teams members."

Movement Detection Improvement
line 170 - "... detection trigger the alarm only on rotation."
line 174 - "... detection on axis x, y."

Battery Management Improvement
line 180 - "... reduce the using consumption."
line 180 - "Turn all component in sleep mode ..."
line 181 - "The electromagnet consume ..."
line 181 - "We will active it less than 1 ..."

Security Improvement
line 185 - "By default the device ..."
line 189 - "We will restreint ..."

Alarm Management
line 195 - "While the alarm is ringing, all others actions are unavailable"
line 195 - "We will modify alarm to make it ringing while others action are executed ..."
line 196 - "We want to reduced the decible from 135dB to 80dB, to readuce damage on the hearing."

NFC Reader
line 200 - "... reader isn't implemented yet, we should include it for an easier usage of the product, make user able to unlock/lock the Sport with a NFC ..."

Errors
line 204 - "The program will must never be stuck on an issue, and continue without this features in the following case:"
line 206 and 208 - "Retrying in few minutes"
line 210 - "Inform client about the issue ..."
line 213 - "An hardware issue is encounter"
line 214 - "The SportShield is run out of battery"

Usage
line 220 - "To Protect you stuff:"
line 238 - "... which you can found"

Performance
line 244 - "... economize battery and wake them up only when it need them."
line 244 - "The code must be exectuted almost fast less than 1s."

Maintainability
line 248 - "... to fit to the new requirements."
line 248 - "Also, if the client want to update it in intern or with another developpement team the code must commented and documented to help to it understanding."

Usability
line 252 - "Although we used a selfmade API to test efficently the program the client can easily replace it by is own API."
line 254 - "This API will receive JSON array cointaing device informations like:"
line 263 - "but we will probably add some usefull information like batterie level ..."

Security
line 267 - "We can update the internal program by plugin on the charging port, it can lead to invalid data target, wrong inform or even more, the disabling of the device or the installation of a malware."

Glossary
line 302 - "... the user informed of device status."
line 303 - "We will used Arduino IDE and a variant of C++ made for arduino during this project."
line 304 - "... variant for C++ specialized to managed their microcontrollers."
line 305 - "... completely language independent but uses conventions that are familiar to programmers of the C-family of languages, including C, C++. 

### Expected result

Persona 1 - Ashley Ricks
line 105 - "She needs to be noticed if someone touches to her skies."

Persona 2 - William Greener 
line 126 - "He wants to get used to use the product."
line 131 - "William needs a product which won't burn under the sun's heat of Canary Islands."

Persona 3 - Steve Sinclair
line 145 - "He wants to protect his stuff while he is not in his camping-car."

Acceptance Criteria 
line 157 - "The Electromagnet mustn't stay locked if the user wants to take back his stuff."
line 159 - I don't understand what you meant.
line 161 - "The Battery must last for 7 days or more."
line 163 - "It must run without any issues. If not, it needs to catch them and alert the user of the error."
line 165 - "To ensure that the project is viable, all the specifications must be approved by the client and the programs must be tested in intern by our Quality Assurance and potentially other team members."

Movement Detection Improvement
line 170 - "... detection triggers the alarm only on rotation."
line 174 - "... detection on axes x, y."

Battery Management Improvement
line 180 - "... reduce the usage consumption."
line 180 - "Turn all components in sleep mode ..."
line 181 - "The electromagnet consumes ..."
line 181 - "We will activate it in less than 1 ..."

Security Improvement
line 185 - "By default, the device ..."
line 189 - "We will restrict ..."

Alarm Management
line 195 - "While the alarm is ringing, all other actions are unavailable"
line 195 - "We will modify the alarm to make it ring while other actions are executed ..."
line 196 - "We want to reduce the decibel from 135dB to 80dB, to reduce damage to the hearing."

NFC Reader
line 200 - "...  reader isn't been implemented yet, we should include it for easier usage of the product, making user able to unlock/lock the Sport with an NFC ..."

Errors
line 204 - "The program must never be stuck on an issue, and continue without these features in the following cases:"
line 206 and 208 - "Retrying in a few minutes"
line 210 - "Inform the client about the issue ..."
line 213 - "A hardware issue is encountered"
line 214 - "The SportShield has run out of battery"

Usage
line 220 - "To Protect your stuff:"
line 238 - "... which you can find"

Performance
line 244 - "... economize the battery and wake them up only when it needs them."
line 244 - "The code must be executed almost fast less than 1s."

Maintainability
line 248 - "... to fit the new requirements."
line 248 - "Also, if the client wants to update it with an intern or with another development team the code must commented on and documented to help its understanding."

Usability
line 252 - "Although we used a self-made API to test efficiently the program the client can easily replace it with its own API."
line 254 - "This API will receive a JSON array containing device information like:"
line 263 - "We will probably add some useful information like battery level ..."

Security
line 267 - "We can update the internal program by the plugin on the charging port, which can lead to invalid data targets, wrong information, or even more, the disabling of the device or the installation of malware."

Glossary
line 302 - "... the user informed of the device status."
line 303 - "We will use Arduino IDE and a variant of C++ made for Arduino during this project."
line 304 - "... variant of C++ specialized to manage their microcontrollers."
line 305 - "... completely language-independent but uses conventions that are familiar to programmers of the C family of languages, including C, and C++. 

### Status

Fail

**Comment by Gregory-Pagnoux** [comment]
new issues on the functional from the line 170 @MathiasGagnepain

**Comment by Gregory-Pagnoux** [comment]
@MathiasGagnepain
- old line in issue = new line in document (expected)
line 174 = 176 (axes), 204 = 206 (cases), "How to use it" have strange rendering, line 248 = 261 (development)(commented on), line 252 = 265(efficiently), line 263 = 276 (useful)(battery), line 267 = 280 (by the plugin on the charging port)(information)(of malware), lin 304 = 317 (variant of C++), line 305 = 318 (language-independent)(C family), including C, and C++)

**Comment by MathiasGagnepain** [comment]
line 176 is not an issue, this is a axe => 🪓 and this is axes => 🪓🪓 :P

**Comment by Gregory-Pagnoux** [comment]
everything seems good
