### ISSUE TITLE
Functional Specifications - Typos

### ISSUE THREAD

**Issue by EnzoGuillouche** [algosup/2023-2024-project-4-sportshield-team-2#3]
### Severity

2 - High

### Issue seen

line 5 - "The goal of the project is to optimize the battery consumption to make keep it alive from 3 days to 7 days"

PROJECT SCOPE
line 66 - "Improve the alarm function to be able to stop it when we want without waiting the loop end."

FUNCTIONAL REQUIREMENTS
line 78 - "Give possibility for user to stop ringing alarm at any moment"

line 80-81 - "All the code must written in the Arduino language (a variant of the C++ programming language), following the existing code convention. No libraries outside of the ones already use in the existing software."

PERSONAS
line 105 - "Ashley needs to be able to let her skies in outdoor lockers without the sportshield freeze."

line 107 - "She needs to by notice if someone touch to her skies."

line 111 - "William is a 37-year-old fan of surfs where I goes everymonth."

line 114 - "He aims to use the product for a while."

line 115 - "He want to secure is surf board."

line 116 - "He want to be able to use it during an entire week-end or during is vacation in the Canary Islands."

line 119 - "Bill needs a product which will not burn in the heat sun of Canary islandes."

line 120 - "He needs a production wich will not run out of battery."

line 121 - "He need a device that is durable and weatherproof to withstand outdoor conditions (Water & Sand)"

line 125 - "Steve Sinclair is a 63-year-old retreated. He is in road trip around the world with his wife, to enjoy his retreat."

line 128 - "He want to protect is stuff will he is not in his camping-car."

line 129 - "He intends to stay alert if someone touch to his stuff but he is not very good with smartphones."

line 132 - "He need to be able to use another way of unlocking than his smartphone."

line 133 - "He intends a hardware which will resist to different climate he can encounter."

### Expected result

line 5 - "The goal of the project is to optimize the consumption to make it last longer, from 3 days to 7 days"

PROJECT SCOPE
line 66 - "Improve the alarm function to be able to stop it whenever we want, either the alarm cycle is finished or not."

FUNCTIONAL REQUIREMENTS
line 78 - "Give possibility for user to make the alarm stop ringing whenever he wants"

line 80-81 - "All the code must be written in the Arduino language (a variant of the C++ programming language), following the existing code convention. No libraries except the ones that have already been given are allowed."

PERSONAS
line 105 - "[. . .] SportShield [. . .]" Then I don't understand the end of the sentence. Did you mean "[. . .] without the SportShield freezing"?

line 107 - "She needs to be noticed if someone touches her skies."

line 111 - "William is a 37 years old fan of surfing and surf places, where he goes every month."

line 114 - "He wants to get used to use the project."

line 115 - "He wants to secure his surf board."

line 116 - "He wants to be able to use it during an entire week-end or during his vacation in the Canary Islands."

line 119 - "Bill needs a product which won't burn under the sun's heat of Canary Islands."

line 120 - "He needs a product which won't often run out of battery."

line 121 - "He needs a durable, weather-resistant device to withstand outdoor conditions. (Water & Sand)"

line 125 - "Steve Sinclair is a 63 year old and is retired. He is in road trip around the world with his wife, to enjoy his retirement."

line 128 - "He wants to protect his stuff while he is not in his camping-car."

line 129 - "He wants to stay alerted if someone touches his stuff but he is not that confident with smartphones."

line 132 - "He needs to be able to use another way to unlock than his smartphone."

line 133 - "He wants a hardware which will resist to different climates he may encounter."

### Status

Fail

**Comment by Gregory-Pagnoux** [comment]
to maintain the consistency :
line 80 - "Arduino language" -> "Arduino's language"
line 118 - "Bill" -> "William"
