### ISSUE TITLE
Functional Specifications Review n°2

### ISSUE THREAD

**Issue by EnzoGuillouche** [algosup/2023-2024-project-4-sportshield-team-2#30]
### Severity

2 - High

### Issue seen

ALL THE DOCUMENT
Conventions are not followed, even two conventions are used in the same array/list.

INTRODUCTION
line 5 - "The goal of the project is to optimize the consumption"

FUNCTIONAL REQUIREMENTS
line 91 - "The SportShield must allow for the following actions:"

USE CASES
Movements & Shocks detection
line 177 - "The user should be notified on his mobile phone and SportShield must ring if the device is movement or rotating."
line 179 - "The device send a notification to the user through the API."
line 180 - "1. The user activate the device in the application. 2. Someone try to stole the user's stuff. 3. The device ring and send a notification. 4. The user receive the notification."
line 181 - "1. If the device is't connected to the network, the status can't be communicated to the app."
line 182 - "2. The device will send a false positive making the user worry."
Battery Status
line 191 - "Every X time the device send the battery state to the App."
line 192 - "If the device is't connected to the network"
Battery is running out
line 199 - "If the device is too low, release the cable and turn it off."
line 202 - "When the battery is low the device send a notification to the user" 
"when the battery is very too low the device release the cable and turn it-self off to prevent irreversible damage on the battery."
line 203 - "If the device is't connected to the network"
line 213 - "When the battery is fully charge the device stop charging and send a notification to the user."
line 214 - "If the device is't connected to the network"
Locking/Unlocking with the mobile app
line 225 - "The user can unlock the sport shield"
line 227 - "The device will wait until it receive a user interaction"
"If it's locked the user ins't able to move it without making ring and he can't get back his stuffs."
Locking/Unlocking with NFC device
line 235 - "The device is now lock or unlock"
line 236 - "it will lock or unlock like by using the mobile app."
line 238 - "If the NFC [[1]](#glossary-1) card isn't working nothing will happend"
"If access right are invalid, the user will be inform of a unsuccessful locking/unlocking attempt"

line 243 - "The Alarm must be deactivatable without waiting if the user made a misstake."
line 247 - "... it need to catch them ..."
line 265 - " We will activate it less than 1 second when we need it."
line 284 - "... making user able to unlock/lock", "... (depending of brand ..."
line 326 - "To open release your stuff."
line 345 - "... with an intern or with another developpement team the code must be commented ..."
line 364 - "... wrong information or even more ..."
line 372 - "We should reverse Engineer the program and comment uncommented stuff."
line 373 - "Hardware issue or code misswriting.", "As a prototype not used very often, the hardware can malfunctionning leading to understandable issue if not detected as soon as possible, and the libraries or API urls can be outdated.", "... if needed before working on it improvement."
line 374 - "... may hinder troubleshooting or leading to inefficiencies or delays."
line 392 - "These Improvements way are just theorical and will not be implemented ..."
line 398 - "The SportShield will be able to be lock or unlock ..."
line 415 - "The only one port to charge the device, it actually can be use also to update the internal software (this action is reserved to Coris)."
line 418 - "Insert the cable here to attache your stuff and protect them."
line 419 - "Make a contact with a NFC device at this place ..."

### Expected result

ALL THE DOCUMENT
Use the same conventions everywhere (includes dots, uppercases, verbs' tense at the beginning, etc.)

INTRODUCTION
line 5 - "The goal of the project is to optimize the battery consumption"

FUNCTIONAL REQUIREMENTS
line 91 - "The SportShield must allow the following actions:"

USE CASES
Movements & Shocks detection
line 177 - "The user should be notified on his mobile phone and SportShield must ring if the device is moving or rotating."
line 179 - "The device sends a notification to the user through the API."
line 180 - "1. The user activates the device in the application. 2. Someone tries to steal the user's stuff. 3. The device rings and sends a notification. 4. The user receives the notification."
line 181 - "1. If the device isn't connected to the network, the status can't be communicated to the app."
line 182 - "2. The device will send a false positive making the user worries."
Battery Status
line 191 - "Every X time the device sends the battery state to the App."
line 192 - "If the device isn't connected to the network"
Battery is running out
line 199 - "If the device depletes its battery, release the cable and turn it off."
line 202 - "When the battery is depleted the device sends a notification to the user" 
"when SportShield has quite depleted its battery the device releases the cable and turns itself off to prevent irreversible damage on the battery."
line 203 - "If the device isn't connected to the network"
line 213 - "When the battery is fully charge the device stops charging and sends a notification to the user."
line 214 - "If the device isn't connected to the network"
Locking/Unlocking with the mobile app
line 225 - "The user can unlock the SportShield"
line 227 - "The device will wait until it receives a user interaction"
"If it's locked the user isn't able to move it without making it ring and he can't get his stuff back."
Locking/Unlocking with NFC device
line 235 - "The device is now locked or unlocked"
line 236 - "it will lock or unlock as well as on the mobile app."
line 238 - "If the NFC card isn't working nothing will happen"
"If access rights are invalid, the user will be informed of a unsuccessful locking/unlocking attempt"

line 243 - "The Alarm must be deactivated without waiting if the user made a mistake."
line 247 - "... it needs to catch them ..."
line 265 - " We will activate it in less than 1 second when we need it."
line 284 - "... making users able to unlock/lock", "... (depending on brand ..."
line 326 - "To open-release your stuff."
line 345 - "... with an intern or with another development team the code must be commented ..."
line 364 - "... wrong information, or even more ..."
line 372 - "We should reverse Engineer the program and comment on uncommented stuff."
line 373 - "Hardware issues or code miswriting.", "As a prototype is not used very often, the hardware can malfunction leading to an understandable issue if not detected as soon as possible, and the libraries or API URLs can be outdated.", "... if needed before working on its improvement."
line 374 - "... may hinder troubleshooting or lead to inefficiencies or delays."
line 392 - "These Improvements way is just theoretical and will not be implemented ..."
line 398 - "The SportShield will be able to be locked or unlocked ..."
line 415 - "The only port to charge the device, it actually can be used also to update the internal software (this action is reserved for Coris)."
line 418 - "Insert the cable here to attach your stuff and protect them."
line 419 - "Make contact with an NFC device at this place ..."

### Status

Fail

**Comment by Gregory-Pagnoux** [comment]
@MathiasGagnepain add issues from line 243 to 419.

**Comment by Gregory-Pagnoux** [comment]
line 202 - "When SportShield has quite depleted its battery the device releases the cable and turns itself off to prevent irreversible damage to the battery."
