### ISSUE TITLE
Test plan - Typos

### ISSUE THREAD

**Issue by robin-debry** [algosup/2023-2024-project-4-sportshield-team-2#32]
### Severity

1 - Critical

### Issue seen

Line 111 - For 5 minutes with the same position, the battery give the minimum of powerful to the bluetooth, in an ambient environment.
Line 113 - modify code to wait 5 secondes
Line 119 - For 5 minutes with the same position, the battery give the minimum of powerful to the bluetooth, in a cold environment.
Line 121 - modify code to wait 5 secondes
Line 128 - The lifespan of the battery is 7 days with 6 hours of operation and 18h in stand-by, in an ambient environment.
Line 130 - write program to power on and power off at good time
Line 131 -unplug the the device
Line 136 - The lifespan of the battery is 7 days with 6 hours of operation and 18h in stand-by, in a cold environment.
Line 138 - write program to power on and power off at good time
Line 139 - unplug the the device
Line 145 The battery reaches 20% level and turn off.
Line 158 Test ID 07: (integreation test)
Line 160 The phone send request to the device to give them password
Line 162 - write program which send "I need password" to the device when the we press "give a password" button
Line 166 The device send an email with the password
Line 168 - write program which send "password given" to an e-mail
Line 173 The device send request which open in the phone a window to put the password given
Line 175 write program to open the windows
Line 181 When the wrong password is enter, print a message
Line 183 - write the password on the window
Line 184 - press "validate" button
Line 189 When the good password is enter, print a message and close the password window
Line 191 - write the password on the window
Line 193 - press "validate" button
Line 196 **Lock / unlock**
Line 206 We can unlock the device, with the device, in a cold environment
Line 228 - press unlock button on the phone
Line 229 - request send to the device by the phone
Line 237 - press unlock button on the phone
Line 238 - request send to the device by the phone
Line 245 - press lock button on the phone
Line 246 - request send to the device by the phone
Line 254 - press lock button on the phone
Line 255 - request send to the device by the phone
Line 276 move the device quikly to have 5 high sounds
Line 280 shock the device to have 5 hiht sounds

### Expected result

Line 111- For 5 minutes in the same position, the battery gives the minimum of power to the Bluetooth, in an ambient environment.
Line 113 - Modify code to wait 5 seconds.
Line 119 - For 5 minutes in the same position, the battery gives the minimum of power to the Bluetooth, in a cold environment.
Line 121 - Modify code to wait 5 seconds.
Line 128 -The lifespan of the battery is 7 days with 6 hours of operation and 18 hours on stand-by, in an ambient environment.
Line 130 - Write a program to power on and power off at a good time.
Line 131 -Unplug the device.
Line 136 - The lifespan of the battery is 7 days with 6 hours of operation and 18 hours on stand-by, in a cold environment.
Line 138 - Write a program to power on and power off at a good time.
Line 139 - Unplug the device.
Line 145 The battery reaches a 20% level and turns off.
Line 158 Test ID 07: (integration test)
Line 160 The phone sends a request to the device to give the password.
Line 162 - Write a program which sends "I need a password" to the device when we press the "give a password" button.
Line 166 The device sends an email with the password
Line 168 - write a program which sends "password given" to an e-mail
Line 173 The device sends a request which opens the application to put the password given
Line 175 - write a program to open the application
Line 181 When the wrong password is entered, print a message.
Line 183 - Write the password on your smartphone.
Line 184 - Press the "validate" button.
Line 189 When the good password is entered, print a message and close the password screen.
Line 191 - Write the password on the window.
Line 193 - Press the "validate" button.
Line 196 **Lock/unlock**
Line 206 We can unlock the device, with device, in a cold environment
Line 228 - Press the unlock button on the phone.
Line 229 - Request sent to the device by the phone
Line 237 - Press the unlock button on the phone
Line 238 - Request sent to the device by the phone
Line 245 - Press lock button on the phone
Line 246 - Request sent to the device by the phone
Line 254 - Press the lock button on the phone
Line 255 - Request sent to the device by the phone
Line 276 move the device quickly to have 5 high sounds
Line 280 shock the device to have 5 high sounds

### Status

Fail

**Comment by Gregory-Pagnoux** [comment]
@robin-debry done
