### ISSUE TITLE
Technical Review - Typos

### ISSUE THREAD

**Issue by Gregory-Pagnoux** [algosup/2023-2024-project-4-sportshield-team-2#78]
### Severity

1 - Critical

### Issue seen

line 58 - "... will therefore be C++ for the most part, as well as a few implementations..."
line 108 - "... have access to hardware ..."
line 124 - "... GALILEO and QZSS ..."
line 147 - "The company is supplying the SIM cards ..."
line 155 - "... has been detected in the last minute."
line 157 - "... 3 types of alarm:"
lines 158 and 159 - "... 0.5 seconds of sound, 0.5 seconds of rest ..."
line 160 - "The third is a high intensity noise ...", "... 1 second of rest and ..."
line 192 - "... sending notifications) are critical ..."
line 217 - "... or detecting movement of the ski ..."

### Expected result

line 58 - "... will therefore be mainly C++, with a few implementations ..."
line 108 - "... have access to the hardware ..."
line 124 - "... GALILEO, and QZSS ..."
line 147 - "The company is supplying SIM cards ..."
line 155 - "... has been detected at the last minute."
line 157 - "... 3 types of alarms:"
lines 158 and 159 - "... 0.5 seconds of sound, and 0.5 seconds of rest ..."
line 160 - "The third is a high-intensity noise ...", "... 1 second of rest, and ..."
line 192 - "... sending notifications) is critical ..." and specify the minimum latency value
line 217 - "... or detecting the movement of the ski ..."

### Status

Fail

**Comment by Gregory-Pagnoux** [comment]
Issues : 
line 52, 183, 186, 189, 192 and 198 Sportshield --> SportShield

For glossary :
line 135 - GNSS sensor
line 139 - HTTP Post request / API / VPS
line 147 - GSM module
line 149 - NFC
line 183 - microcontroller-based / Arduino
line 186 - IDE
line 192 - C++
line 195 - open-source libraries
line 209 - IMU
line 217 - I2C
line 222 - NMEA

**Comment by HiNett** [comment]
Good !
