### ISSUE TITLE
issues in user manual review

### ISSUE THREAD

**Issue by MathiasGagnepain** [algosup/2023-2024-project-4-sportshield-team-2#85]
### Severity

4 - Low

### Issue seen

https://github.com/algosup/2023-2024-project-4-sportshield-team-2/blob/aa464e749de6f1caa82c17393ce918fa7864fb7e/Documents/UserManual/userManual.md?plain=1#L48

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8BDHcDHT8kqjjWvqSohD9jyvMkO4aU7jqJ3bhzcwJ3w&s)

### Expected result

Add a period at the end of the sentence.

### Status

Fail

**Comment by EnzoGuillouche** [comment]
Fixed in commit.
