### ISSUE TITLE
Theorial Calculation - Typos

### ISSUE THREAD

**Issue by Gregory-Pagnoux** [algosup/2023-2024-project-4-sportshield-team-2#90]
### Severity

1 - Critical

### Issue seen

line 3 - "This document aim ...", "... the battery by the theorical way ..."
line 65 - "In work time ...", "... send a data every ..."
line 79 - "In sleep mode ...", "... send a data every ..."
line 99 - "... alarms hasn't been ...", "...  taken in consideration ...", "... depends of how ..."
line 100 - "... hours of works and ..."
line 110 - "... for approximatly 4,8 days."
line 111 - "With our own battery ...", "... for approximatly 16,1 days."
line 152 - "... the top of module"
line 177 - "Power module ...", "... homing network"
line 178 - "... all the way .", "... The pins has golden ...", "... we send it by ramdonly"
line 206 - "No real information found ...", "... due to an unknow brand ..."
line 234 - "It's not consume ...", "... by itself it's depend of the connected ..."

### Expected result

line 3 - "This document aims ...", "... the battery in a theoretical way ..."
line 65 - "During work time ...", "... send data every ..."
line 65 - "During sleep mode, ...", "... send data every ..."
line 99 - "... alarms haven't been ...", "...  taken into consideration ...", "... depends on how ..."
line 100 - "... hours of work and ..."
line 110 - "... for approximately 4,8 days."
line 111 - "With our battery ...", "... for approximately 16,1 days."
line 152 - "... the top of the module"
line 177 - "The power module ...", "... homing the network"
line 178 - "... all the way.", "... The pins are golden ...", "... we send them by randomly"
line 206 - "No real information was found ...", "... due to an unknown brand ..."
line 234 - "It doesn't consume ...", "... by itself it depends on  the connected ..."

### Status

Fail

**Comment by MathiasGagnepain** [comment]
I didn't understood the error line 234 cause the part starting at "...is provide ..." doesn't exist in my documents and has never exist in it :(

**Comment by Gregory-Pagnoux** [comment]
@MathiasGagnepain 
You need to change the name of the document and the line 1 in Theoretical Calculations

**Comment by Gregory-Pagnoux** [comment]
@MathiasGagnepain 

Calculations issues:
line 44 - "The buzzer consumes 10mA/h."
⚠️pay attention to rounding!
⚠️pay attention to the typo of the decimal! It's a dot and not a comma.
line 45 - "10 / 60 ≃ 0.17mA/minute"
line 46 - "0.17 / 60 ≃ 0.0028mA/second = 2.8µA/second"
line 69 - "4 x 291µA = 1 164µA/h ≃ 1.16mA/h"
line 76 - "2/60 ≃ 0.033 mA = 33µA/minute"
line 85 - "2mA - 0.00165mA = 1.99835mA/h"
line 89 - "2mA - 0.0066mA = 1.9934mA/h"
line 93 - "200mA + 30mA + 350mA + 425mA + 10mA = 1015mA/h"
line 95 - "5µA + 18µA + 2mA = 0.005mA + 0.018mA + 2mA = 2.023mA/h"
line 96 - "5µA + 28mA + 1.9934mA + 1.17mA = 0.005mA + 28mA + 1.9934mA + 1.17mA = 31.1684mA/h
line 97 - "5µA + 18µA + 1.99835mA + 291µA = 0.005mA + 0.018mA + 1.99835mA + 0.291mA = 2.31235mA/h"
line 103 - "6 x 31.1684mA = 187.0104mA"
line 106 - "187.0104mA + 41,6223 = 228,6327mA"
line 108 - "We have a total consumption of 228,6327mA per day."
